# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "generic/rocky9"
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.provider "virtualbox" do |vb_vm1|
      vb_vm1.gui = true
      vb_vm1.memory = "1024"
    end
    vm1.vm.box = "rocky-ynov"
    vm1.vm.network "private_network", ip: "10.1.1.11"
    vm1.vm.box_check_update = false
    vm1.vm.synced_folder ".", "/vagrant", disabled: true
    vm1.vm.provision "shell", path: "setup.sh"
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.provider "virtualbox" do |vb_vm2|
      vb_vm2.gui = true
      vb_vm2.memory = "1024"
    end
    vm2.vm.box = "rocky-ynov"
    vm2.vm.network "private_network", ip: "10.1.1.12"
    vm2.vm.box_check_update = false
    vm2.vm.synced_folder ".", "/vagrant", disabled: true
    vm2.vm.provision "shell", path: "setup.sh"
  end
end
