- name: Install nginx
  hosts: web
  become: true

  tasks:
  - name: Install nginx
    dnf:
      name: nginx
      state: present

  - name: Copie certificat et clé
    copy:
      src: '{{ item }}'
      dest: "/etc/pki/tls/{{ 'certs' if 'crt' in item else 'private' }}/{{ item }}"
      mode: '0600'
    with_items:
       - 'nginx.crt'
       - 'nginx.key'

  - name: Create directory tp1_site
    file:
      path: /var/www/tp1_site
      state: directory

  - name: Insert Index Page
    copy:
      dest: /var/www/tp1_site/index.html
      content: "<h1>Coucou toi !</h1>"

  - name: Déploiement du fichier de configuration NGINX
    copy:
      src: nginx.conf
      dest: /etc/nginx/conf.d/tp1_site.conf

  - name: Firewall
    firewalld:
      permanent: yes
      immediate: yes
      port: "443/tcp"
      state: enabled

  - name: Start NGINX
    service:
      name: nginx
      state: started
